### PR TITLE
fix: Calculate the RecordSchema's `lookup` table on build

### LINKED ISSUE #403: `RecordSchema::builder()` requires `fields` and `lookup` to be set
```rust
RecordSchema::builder().name(Name::new("Something").unwrap()).build()
```
This is a compile error.

I think `fields` should be allowed to be empty, and that `lookup` should not be able to be set by the user and shoud instead be derived from `fields`.

### PR DESCRIPTION
**Pull request by martin-g**
Fixes #403

### CODE REVIEW

File: avro/src/schema/record/schema.rs [hunk 1]
```diff
@@ -49,3 +59,105 @@ pub(crate) enum RecordSchemaParseLocation {
...
+    use apache_avro_test_helper::TestResult;
+    use pretty_assertions::assert_eq;
+
+    #[test]
+    fn avro_rs_403_record_schema_builder_no_fields() -> TestResult {
+        let name = Name::new("TestRecord")?;
+
+        let record_schema = RecordSchema::builder()
+            .name(name.clone())
+            .fields(vec![])
```
Comment (martin-g) [inline avro/src/schema/record/schema.rs]: I does not make much sense to have a RecordSchema without fields but it was possible until now, so I left it as is.

Comment (Kriskras99) [reply avro/src/schema/record/schema.rs]: It's actually useful for dealing with Rust enums (https://github.com/apache/avro-rs/issues/365#issuecomment-3730627801)

File: avro/src/schema/record/schema.rs [hunk 2]
```diff
@@ -34,12 +34,22 @@ pub struct RecordSchema {
     pub fields: Vec<RecordField>,
```
Comment (Kriskras99) [inline avro/src/schema/record/schema.rs:35]:
```suggestion
    #[builder(default)]
    pub fields: Vec<RecordField>,
```

File: avro/src/schema/record/schema.rs [hunk 3]
```diff
@@ -34,12 +34,22 @@ pub struct RecordSchema {
...
     /// The `lookup` table maps field names to their position in the `Vec`
     /// of `fields`.
+    #[builder(skip = calculate_lookup_table(&fields))]
     pub lookup: BTreeMap<String, usize>,
     /// The custom attributes of the schema
-    #[builder(default = BTreeMap::new())]
+    #[builder(default = Default::default())]
```
Comment (Kriskras99) [inline avro/src/schema/record/schema.rs]:
```suggestion
    #[builder(default)]
```

**Review by Kriskras99 — APPROVED** [review]
