### PR TITLE
fix!: Remove unused fields in `RecordField` (`order`, `position`)

### LINKED ISSUE #490: Remove `RecordField` `position` and `order`
Both fields aren't really used in the code, and make the existing code more complex.
`order` has in its documentation that it is not used.
`position` is only used in the `SchemaAwareWriteSerializer` where the value could also have been passed in as a function argument from the parent function.

Needing to fill the `position` fields make generating code in `avro_derive` significantly complex. So removing it would simplify a lot of code (we would also need to generate less code which makes `T::get_schema()` faster at runtime).

@martin-g what do you think?

### PR DESCRIPTION
**Pull request by Kriskras99**
Also changes the type of `aliases` from `Option<Vec<String>>` to `Vec<String>`.

I've changed almost all the places where we instantiate `RecordField` to use the builder syntax which is less verbose.
I've also removed two tests that were testing the `position` field.

Closes #490

### CODE REVIEW

File: avro/src/schema/record/field.rs [hunk 1]
```diff
@@ -67,38 +58,32 @@ impl Debug for RecordField {
...
-        // This field is ignored as it currently has no effect
-        // debug.field("order", &self.order);
-        debug.field("position", &self.position);
         if !self.custom_attributes.is_empty() {
             debug.field("custom_attributes", &self.custom_attributes);
         }
-        // As we are always skipping self.order, always show the ..
-        debug.finish_non_exhaustive()
+        if self.doc.is_none()
+            || !self.aliases.is_empty()
```
Comment (martin-g) [inline avro/src/schema/record/field.rs]:
```suggestion
            || self.aliases.is_empty()
```

File: avro/src/serde/derive.rs
Comment (martin-g) [inline avro/src/serde/derive.rs]:
```suggestion
///    and `fn get_record_fields_in_ctxt(&mut HashSet<Name>, &Namespace) -> Option<Vec<RecordField>>` in the module provided
```

File: avro/src/serde/ser_schema/mod.rs [hunk 2]
```diff
@@ -373,52 +378,45 @@ impl<W: Write> ser::SerializeStruct for SchemaAwareWriteSerializeStruct<'_, '_,
...
-                Details::SerializeRecordFieldWithSchema {
-                    field_name: key.to_string(),
-                    record_schema: Schema::Record(self.record_schema.clone()),
-                    error: Box::new(e),
-                }
-                .into()
-            }),
-            None => Err(Details::FieldName(String::from(key)).into()),
+        if let Some(position) = self.record_schema.lookup.get(key).copied() {
+            let field = &self.record_schema.fields[position];
```
Comment (martin-g) [inline avro/src/serde/ser_schema/mod.rs]: Is it always safe to make this index lookup ?
The previous version uses `.get()`

Comment (Kriskras99) [reply avro/src/serde/ser_schema/mod.rs]: Nope, reverted to use `.get()`.

I do think it would be good to make the `fields` and `lookup` fields of `RecordSchema` private and improve the builder.
