### PR TITLE
fix!: Stricter schema parsing

### LINKED ISSUE #476: `type.enum` is valid while it should fail, good is `type.type.enum` according to spec
Hi, a schema like this is parsed correctly by avro-rs, this tests fails (it should err):

```rs
fn test_wrong_enum() {
    let schema_str = r#"{
        "type": "record",
        "name": "ExampleEnum",
        "namespace": "com.schema",
        "fields": [
            {
            "name": "wrong_enum",
            "type": "enum",
            "symbols": ["INSERT", "UPDATE"]
            }
        ]
    }"#;
    let result = Schema::parse_str(schema_str);
    assert!(result.is_err());
}
```

While tools like `avro-tools` fail to create the enums with this schema.

The problem is that `enum` should be defined inside `enum`, this would be a good looking example.
Notice the `type.type.enum`:

```json
{
  "type": "record",
  "name": "ExampleEnum",
  "namespace": "com.schema",
  "fields": [
    {
      "name": "wrong_enum",
      "type": {
        "name": "WrongEnum",
        "type": "enum",
        "symbols": ["INSERT", "UPDATE"]
      }
    }
  ]
}
```

I couldn't find any example in the specification of `type.enum`, and given that `avro-tools` fails to generate the java code, I assume `type.enum` is wrong. Let me know if that's not the case.

Best.

### PR DESCRIPTION
**Pull request by Kriskras99**
This will break code, as it no longer accepts invalid schemas.

Closes #476

### CODE REVIEW

File: avro/src/schema/mod.rs [hunk 1]
```diff
@@ -3815,20 +3799,10 @@ mod tests {
...
-        let result = Schema::parse_str(schema_str);
-        assert!(result.is_err());
-        let err = result
-            .map_err(|e| e.to_string())
-            .err()
-            .unwrap_or_else(|| "unexpected".to_string());
-        assert_eq!(expected, err);
+        assert_eq!(
+            Schema::parse_str(schema_str).unwrap_err().to_string(),
+            "`default`'s value type of field `f1` in `ns.record1` must be a `{\"name\":\"ns.record2\",\"type\":\"record\",\"fields\":[{\"name\":\"f1_1\",\"type\":\"int\"}]}`. Got: String(\"invalid\")"
```
Comment (martin-g) [inline avro/src/schema/mod.rs]: nit: Let's use raw string to make a bit more readable. `r#"..."#`
Same for the other similar assertions.

File: avro/src/schema/mod.rs [hunk 2]
```diff
@@ -5438,4 +5401,26 @@ mod tests {
...
+                "name": "wrong_enum",
+                "type": "enum",
+                "symbols": ["INSERT", "UPDATE"]
+                }
+            ]
+        }"#;
+        let result = Schema::parse_str(schema_str).unwrap_err();
+        assert_eq!(
+            result.to_string(),
+            "Invalid schema: There is no type called 'enum', if you meant to define a non-primitive schema, it should be defined inside `type` attribute. Please review the specification"
```
Comment (martin-g) [inline avro/src/schema/mod.rs]:
```suggestion
            "Invalid schema: There is no type called 'enum', if you meant to define a non-primitive schema, it should be defined inside `type` attribute. Please consult with the specification"
```

File: avro/src/error.rs [hunk 3]
```diff
@@ -405,6 +405,9 @@ pub enum Details {
     #[error("No `type` in complex type")]
     GetComplexTypeField,
 
+    #[error("No `type` in in record field")]
```
Comment (martin-g) [inline avro/src/error.rs]:
```suggestion
    #[error("No `type` in record field")]
```

File: avro/src/schema/record/field.rs [hunk 4]
```diff
@@ -81,12 +80,14 @@ impl RecordField {
...
-            field,
-            &enclosing_record.namespace,
-            RecordSchemaParseLocation::FromField,
-        )?;
+        let ty = field.get("type").ok_or(Details::GetRecordFieldTypeField)?;
+        let schema = parser.parse(ty, &enclosing_record.namespace)?;
+
+        if let Some(logical_type) = field.get("logicalType") {
+            warn!(
+                "Ignored the {enclosing_record}.logicalType property (`{logical_type}`). It should probably be nested instide the `type` for the field"
```
Comment (martin-g) [inline avro/src/schema/record/field.rs]:
```suggestion
                "Ignored the {enclosing_record}.logicalType property (`{logical_type}`). It should probably be nested inside the `type` for the field"
```

File: avro/src/schema/record/field.rs
Comment (martin-g) [inline avro/src/schema/record/field.rs]: This needs reworking too.
`logicalType`, `symbols`, `size`, `items` and `values` cannot be at that level anymore.

File: avro/src/schema/record/field.rs [hunk 5]
```diff
@@ -162,10 +163,14 @@ impl RecordField {
...
 
                     if !resolved {
+                        let schemata = names.values().cloned().collect::<Vec<_>>();
                         return Err(Details::GetDefaultRecordField(
                             field_name.to_string(),
                             record_name.to_string(),
-                            field_schema.canonical_form(),
+                            field_schema
+                                .independent_canonical_form(&schemata)
+                                .unwrap_or("Unknown".to_string()),
```
Comment (martin-g) [inline avro/src/schema/record/field.rs]: How about falling back to the canonical form instead of this "Unknown" ?

**Review by martin-g — COMMENTED** [review]
Here are some comments on the proposed changes in this PR.

But as I commented at https://github.com/apache/avro-rs/issues/476#issuecomment-3943071557 the Java and Python SDKs do support parsing such flat schemas too.

File: avro/src/schema/mod.rs (hunk 2 above)
Comment (Kriskras99) [reply avro/src/schema/mod.rs]: I've removed the entire `Please review the specification`/`Please consult with the specification` bit

File: avro/src/schema/record/field.rs
Comment (Kriskras99) [reply avro/src/schema/record/field.rs]: I've also removed the `position` field, as it is not in the spec or used in the code.

File: avro/src/schema/record/field.rs (hunk 5 above)
Comment (Kriskras99) [reply avro/src/schema/record/field.rs]: Great idea!

**Review by martin-g — APPROVED** [review]
